[2025-05-08T14:06:31.284+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T14:05:57.809227+00:00 [queued]>
[2025-05-08T14:06:31.323+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T14:05:57.809227+00:00 [queued]>
[2025-05-08T14:06:31.324+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-08T14:06:31.349+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_gold_data> on 2025-05-08 14:05:57.809227+00:00
[2025-05-08T14:06:31.379+0000] {standard_task_runner.py:57} INFO - Started process 5793 to run task
[2025-05-08T14:06:31.400+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'transform_gold_data', 'manual__2025-05-08T14:05:57.809227+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpa9e3eyns']
[2025-05-08T14:06:31.416+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask transform_gold_data
[2025-05-08T14:06:31.578+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T14:05:57.809227+00:00 [running]> on host 223a2d167166
[2025-05-08T14:06:31.886+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='transform_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T14:05:57.809227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T14:05:57.809227+00:00'
[2025-05-08T14:06:31.891+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/gold_prices/2025-05-08.csv'.
[2025-05-08T14:06:31.972+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/fed_rates/2025-05-08.csv'.
[2025-05-08T14:06:32.009+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/sp500/2025-05-08.csv'.
[2025-05-08T14:06:32.133+0000] {logging_mixin.py:151} INFO - Columns in merged_df: ['date', 'source_name', 'ticker_symbol', 'open_price', 'prix_or', 'volume_or', 'ingestion_timestamp', 'prix_sp500', 'volume_sp500', 'taux_fed']
[2025-05-08T14:06:32.135+0000] {logging_mixin.py:151} INFO - Shape of merged_df: (186, 10)
[2025-05-08T14:06:32.153+0000] {logging_mixin.py:151} INFO - Sample of merged_df:
                        date source_name ticker_symbol  open_price  prix_or  volume_or ingestion_timestamp  prix_sp500  volume_sp500  taux_fed
0 2025-04-08 00:00:00.090904         NaN           NaN         NaN      NaN        NaN                 NaN         NaN           NaN      4.33
1 2025-04-08 04:00:00.090904         NaN           NaN         NaN      NaN        NaN                 NaN         NaN           NaN      4.33
2 2025-04-08 08:00:00.090904         NaN           NaN         NaN      NaN        NaN                 NaN         NaN           NaN      4.33
3 2025-04-08 12:00:00.090904         NaN           NaN         NaN      NaN        NaN                 NaN         NaN           NaN      4.33
4 2025-04-08 16:00:00.090904         NaN           NaN         NaN      NaN        NaN                 NaN         NaN           NaN      4.33
[2025-05-08T14:06:32.166+0000] {logging_mixin.py:151} INFO - Shape of merged_df after dropna: (0, 10)
[2025-05-08T14:06:32.167+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform.py", line 95, in transform_gold_data
    raise ValueError("prix_or column is empty after processing. Cannot calculate price variation.")
ValueError: prix_or column is empty after processing. Cannot calculate price variation.
[2025-05-08T14:06:32.188+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_pipeline, task_id=transform_gold_data, execution_date=20250508T140557, start_date=20250508T140631, end_date=20250508T140632
[2025-05-08T14:06:32.224+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task transform_gold_data (prix_or column is empty after processing. Cannot calculate price variation.; 5793)
[2025-05-08T14:06:32.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-08T14:06:32.330+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
