[2025-05-20T17:33:39.989+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_spark_logs.check_spark_logs manual__2025-05-20T17:33:39.281921+00:00 [queued]>
[2025-05-20T17:33:40.002+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_spark_logs.check_spark_logs manual__2025-05-20T17:33:39.281921+00:00 [queued]>
[2025-05-20T17:33:40.003+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T17:33:40.067+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_spark_logs> on 2025-05-20 17:33:39.281921+00:00
[2025-05-20T17:33:40.078+0000] {standard_task_runner.py:57} INFO - Started process 283 to run task
[2025-05-20T17:33:40.092+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monitor_spark_logs', 'check_spark_logs', 'manual__2025-05-20T17:33:39.281921+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/monitor_spark.py', '--cfg-path', '/tmp/tmp7lr4bh8d']
[2025-05-20T17:33:40.099+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask check_spark_logs
[2025-05-20T17:33:40.183+0000] {task_command.py:415} INFO - Running <TaskInstance: monitor_spark_logs.check_spark_logs manual__2025-05-20T17:33:39.281921+00:00 [running]> on host 6bb1f84c11d3
[2025-05-20T17:33:40.334+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_spark_logs' AIRFLOW_CTX_TASK_ID='check_spark_logs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T17:33:39.281921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T17:33:39.281921+00:00'
[2025-05-20T17:33:40.337+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T17:33:40.339+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec gold_price_project-spark-1 bash -c \'\n        if grep -Ei "error|exception|traceback" /scripts/logs/spark.log; then\n            echo "❌ Erreur détectée dans spark.log"\n            curl -X POST -H "Content-Type: application/json"             -d "{\\"content\\":\\"❌ Erreur détectée dans spark.log ! Vérifiez le pipeline à {$(date +"%Y-%m-%d %H:%M:%S")}.\\"}"             https://discord.com/api/webhooks/1374382502981931008/BRaqnl_BHNxEep-dItvMinlhhcd9Tk5-sj3RbKdG3qDzLjwfYGRze8IZTxRoaiQj0DE2\n        else\n            echo "✅ Aucun problème détecté dans spark.log"\n        fi\n        \'\n        ']
[2025-05-20T17:33:40.353+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T17:33:40.495+0000] {subprocess.py:93} INFO - exception
[2025-05-20T17:33:40.496+0000] {subprocess.py:93} INFO - ❌ Erreur détectée dans spark.log
[2025-05-20T17:33:40.666+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-05-20T17:33:40.668+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-05-20T17:33:41.274+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   100    0     0  100   100      0    164 --:--:-- --:--:-- --:--:--   163100   100    0     0  100   100      0    164 --:--:-- --:--:-- --:--:--   163
[2025-05-20T17:33:41.295+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-20T17:33:41.343+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monitor_spark_logs, task_id=check_spark_logs, execution_date=20250520T173339, start_date=20250520T173339, end_date=20250520T173341
[2025-05-20T17:33:41.394+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-20T17:33:41.417+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
