[2025-05-17T15:11:48.528+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.load_gold_data manual__2025-05-17T15:10:15.233685+00:00 [queued]>
[2025-05-17T15:11:48.545+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.load_gold_data manual__2025-05-17T15:10:15.233685+00:00 [queued]>
[2025-05-17T15:11:48.546+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-17T15:11:48.568+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_gold_data> on 2025-05-17 15:10:15.233685+00:00
[2025-05-17T15:11:48.577+0000] {standard_task_runner.py:57} INFO - Started process 874 to run task
[2025-05-17T15:11:48.581+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'load_gold_data', 'manual__2025-05-17T15:10:15.233685+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpcjevxaaz']
[2025-05-17T15:11:48.584+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask load_gold_data
[2025-05-17T15:11:48.647+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.load_gold_data manual__2025-05-17T15:10:15.233685+00:00 [running]> on host 75a565b94570
[2025-05-17T15:11:48.774+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='load_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T15:10:15.233685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-17T15:10:15.233685+00:00'
[2025-05-17T15:11:51.627+0000] {logging_mixin.py:151} INFO - Permissions définies avec succès sur /gold_datalake/processed (777)
[2025-05-17T15:11:51.628+0000] {client.py:724} INFO - Reading file '/gold_datalake/processed/gold_prices_2025-05-17.parquet'.
[2025-05-17T15:11:51.724+0000] {logging_mixin.py:151} INFO - Fichier Parquet lu avec succès depuis HDFS: /gold_datalake/processed/gold_prices_2025-05-17.parquet
[2025-05-17T15:11:51.725+0000] {client.py:724} INFO - Reading file '/gold_datalake/processed/dim_date_2025-05-17.parquet'.
[2025-05-17T15:11:51.755+0000] {logging_mixin.py:151} INFO - Fichier Parquet lu avec succès depuis HDFS: /gold_datalake/processed/dim_date_2025-05-17.parquet
[2025-05-17T15:11:51.756+0000] {client.py:724} INFO - Reading file '/gold_datalake/processed/dim_marche_2025-05-17.parquet'.
[2025-05-17T15:11:51.780+0000] {logging_mixin.py:151} INFO - Fichier Parquet lu avec succès depuis HDFS: /gold_datalake/processed/dim_marche_2025-05-17.parquet
[2025-05-17T15:11:51.840+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2025-05-17T15:11:51.842+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-17T15:11:51.842+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2025-05-17T15:11:54.662+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2025-05-17T15:11:54.766+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:54.767+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:54.785+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2025-05-17T15:11:54.885+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:54.886+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:54.891+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_DATE"...]
[2025-05-17T15:11:54.978+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:55.014+0000] {cursor.py:804} INFO - query: [CREATE TABLE "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_DATE" ( date_id datetime, jour I...]
[2025-05-17T15:11:55.159+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:55.160+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:55.193+0000] {cursor.py:804} INFO - query: [INSERT INTO "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_DATE" (date_id, jour, mois, annee...]
[2025-05-17T15:11:57.516+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:57.518+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:get_table_names */ TABLES IN "GOLD_ANALYSIS"."MARCHE"]
[2025-05-17T15:11:57.624+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:57.628+0000] {cursor.py:959} INFO - Number of results in first chunk: 4
[2025-05-17T15:11:57.634+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/load.py:168 UserWarning: The provided table name 'TEMP_DIM_DATE' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2025-05-17T15:11:57.636+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:11:57.820+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:57.821+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:57.822+0000] {cursor.py:804} INFO - query: [MERGE INTO GOLD_ANALYSIS.MARCHE.DIM_DATE AS target USING GOLD_ANALYSIS.MARCHE.TE...]
[2025-05-17T15:11:58.202+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:58.203+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:11:58.373+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:58.374+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:58.375+0000] {cursor.py:804} INFO - query: [DROP TABLE IF EXISTS GOLD_ANALYSIS.MARCHE.TEMP_DIM_DATE]
[2025-05-17T15:11:58.494+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:58.495+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:58.497+0000] {logging_mixin.py:151} INFO - Table Dim_Date mise à jour avec succès dans Snowflake (sans doublons)
[2025-05-17T15:11:58.500+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_MARCH...]
[2025-05-17T15:11:58.585+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:58.590+0000] {cursor.py:804} INFO - query: [CREATE TABLE "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_MARCHE" ( date_id datetime, volu...]
[2025-05-17T15:11:58.744+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:11:58.745+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:11:58.766+0000] {cursor.py:804} INFO - query: [INSERT INTO "GOLD_ANALYSIS"."MARCHE"."TEMP_DIM_MARCHE" (date_id, volume_sp500, m...]
[2025-05-17T15:12:00.182+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:00.184+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:get_table_names */ TABLES IN "GOLD_ANALYSIS"."MARCHE"]
[2025-05-17T15:12:00.296+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:00.298+0000] {cursor.py:959} INFO - Number of results in first chunk: 4
[2025-05-17T15:12:00.302+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/load.py:189 UserWarning: The provided table name 'TEMP_DIM_MARCHE' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2025-05-17T15:12:00.305+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:12:00.503+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:00.504+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:00.506+0000] {cursor.py:804} INFO - query: [MERGE INTO GOLD_ANALYSIS.MARCHE.DIM_MARCHE AS target USING GOLD_ANALYSIS.MARCHE....]
[2025-05-17T15:12:00.918+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:00.919+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:12:01.103+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:01.107+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:01.112+0000] {cursor.py:804} INFO - query: [DROP TABLE IF EXISTS GOLD_ANALYSIS.MARCHE.TEMP_DIM_MARCHE]
[2025-05-17T15:12:01.238+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:01.239+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:01.240+0000] {logging_mixin.py:151} INFO - Table Dim_Marche mise à jour avec succès dans Snowflake (sans doublons)
[2025-05-17T15:12:01.244+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ "GOLD_ANALYSIS"."MARCHE"."TEMP_FAIT_PRIX...]
[2025-05-17T15:12:01.354+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:01.361+0000] {cursor.py:804} INFO - query: [CREATE TABLE "GOLD_ANALYSIS"."MARCHE"."TEMP_FAIT_PRIX_OR" ( date_id datetime, pr...]
[2025-05-17T15:12:01.518+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:01.519+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:01.592+0000] {cursor.py:804} INFO - query: [INSERT INTO "GOLD_ANALYSIS"."MARCHE"."TEMP_FAIT_PRIX_OR" (date_id, prix_or, volu...]
[2025-05-17T15:12:02.220+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:02.232+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:get_table_names */ TABLES IN "GOLD_ANALYSIS"."MARCHE"]
[2025-05-17T15:12:02.339+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:02.342+0000] {cursor.py:959} INFO - Number of results in first chunk: 4
[2025-05-17T15:12:02.352+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/load.py:207 UserWarning: The provided table name 'TEMP_FAIT_PRIX_OR' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2025-05-17T15:12:02.356+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:12:02.565+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:02.574+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:02.576+0000] {cursor.py:804} INFO - query: [MERGE INTO GOLD_ANALYSIS.MARCHE.FAIT_PRIX_OR AS target USING GOLD_ANALYSIS.MARCH...]
[2025-05-17T15:12:02.969+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:02.972+0000] {cursor.py:804} INFO - query: [COMMIT]
[2025-05-17T15:12:03.153+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:03.154+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:03.156+0000] {cursor.py:804} INFO - query: [DROP TABLE IF EXISTS GOLD_ANALYSIS.MARCHE.TEMP_FAIT_PRIX_OR]
[2025-05-17T15:12:03.277+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:03.278+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:03.279+0000] {logging_mixin.py:151} INFO - Table Fait_Prix_Or mise à jour avec succès dans Snowflake (sans doublons)
[2025-05-17T15:12:03.280+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2025-05-17T15:12:03.363+0000] {cursor.py:817} INFO - query execution done
[2025-05-17T15:12:03.364+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2025-05-17T15:12:03.364+0000] {logging_mixin.py:151} INFO - Connexion Snowflake fermée
[2025-05-17T15:12:03.366+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-17T15:12:03.380+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=gold_pipeline, task_id=load_gold_data, execution_date=20250517T151015, start_date=20250517T151148, end_date=20250517T151203
[2025-05-17T15:12:03.441+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-17T15:12:03.476+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
